-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : jeu. 02 mai 2024 à 20:48
-- Version du serveur : 10.4.32-MariaDB
-- Version de PHP : 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `paraabir`
--

-- --------------------------------------------------------

--
-- Structure de la table `produits`
--

CREATE TABLE `produits` (
  `id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `type` varchar(30) NOT NULL,
  `description` varchar(500) NOT NULL,
  `src` varchar(200) NOT NULL,
  `price` int(11) NOT NULL,
  `qte` int(11) DEFAULT 20,
  `company` varchar(30) DEFAULT NULL,
  `qtecart` int(11) DEFAULT 0,
  `marque` varchar(25) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `produits`
--

INSERT INTO `produits` (`id`, `title`, `type`, `description`, `src`, `price`, `qte`, `company`, `qtecart`, `marque`) VALUES
(5, 'essence-daily-Drop-of-BEAUTY-SLEEP-AMPOULE-FACE-SERUM', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'essence-daily-Drop-of-BEAUTY-SLEEP-AMPOULE-FACE-SERUM.webp', 120, 20, 'Avene', 1, 'A-DERMA'),
(6, 'abcderm-cold-cream', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'abcderm-cold-cream.jpg', 120, 20, 'Avene', 1, 'A-DERMA'),
(7, 'absolute-hydrate-me-face-primer-parfumerie', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'absolute-hydrate-me-face-primer-parfumerie.jpg', 120, 20, 'Benecos', 1, 'A-DERMA'),
(8, 'argiletz-argile-verte-surfine', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'argiletz-argile-verte-surfine.webp', 120, 20, 'Avene', 1, 'A-DERMA'),
(9, 'Bioderma-Photoderm-Max-Fluid-SPF100-40ml-nova', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Bioderma-Photoderm-Max-Fluid-SPF100-40ml-nova.webp', 150, 20, 'Eucerin', 1, 'ACORELLE'),
(10, 'cattier-creme-protection-solaire-teintee-spf-50-bio-40-ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'cattier-creme-protection-solaire-teintee-spf-50-bio-40-ml.jpg', 180, 20, 'Nuxe', 1, 'ACORELLE'),
(11, 'cerave-creme-hydratante-spf-25-visage-52-ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'cerave-creme-hydratante-spf-25-visage-52-ml.jpg', 280, 20, 'Benecos', 1, 'A-DERMA'),
(12, 'Creme-Spf50-50ml-3282779402781-avene', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Creme-Spf50-50ml-3282779402781-avene.jpg', 210, 20, 'Nuxe', 1, 'ACORELLE'),
(13, 'Daylong-Face-Fluide-Regulateur-SPF-50_-50ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Daylong-Face-Fluide-Regulateur-SPF-50_-50ml.webp', 210, 20, 'Eucerin', 1, 'ACORELLE'),
(14, 'daylong-sensitive-face-bb-solaire-perfecteur-spf-50-fluide-teinte', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'daylong-sensitive-face-bb-solaire-perfecteur-spf-50-fluide-teinte.webp', 200, 20, 'Benecos', 1, 'ALBADERME'),
(15, 'Daylong-Sensitive-Face-Gel-SPF50_-50ml-nova', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Daylong-Sensitive-Face-Gel-SPF50_-50ml-nova.webp', 200, 20, 'Avene', 1, 'A-DERMA'),
(16, 'dr-organic-masque-visage-au-cafe-125ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'dr-organic-masque-visage-au-cafe-125ml.jpg', 130, 20, 'Eucerin', 1, 'ALBADERME'),
(17, 'Ducray-dexyane-gel-nettoyant-visage-_-corps-400ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Ducray-dexyane-gel-nettoyant-visage-_-corps-400ml.webp', 130, 20, 'Bingo', 1, 'ACORELLE'),
(18, 'Eptaderm-Creme-Visage-50-ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Eptaderm-Creme-Visage-50-ml.webp', 180, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(19, 'Exfoliac-Gel-moussant-doux-200-ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Exfoliac-Gel-moussant-doux-200-ml.jpg', 180, 20, 'Bingo', 1, 'A-DERMA'),
(20, 'la-roche-posay-gommage-surfin-physiologique-50ml-lisse-et-assainit-en-douceur', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'la-roche-posay-gommage-surfin-physiologique-50ml-lisse-et-assainit-en-douceur.webp', 220, 20, 'Eucerin', 1, 'ALBADERME'),
(21, 'md-photowhite-correcteur-de-teint-n11-spf20-20ml', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'md-photowhite-correcteur-de-teint-n11-spf20-20ml.webp', 220, 20, 'Benecos', 1, 'A-DERMA'),
(22, 'Neostrata-Bionic-Face-Cream-12', 'face', 'Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.', 'Neostrata-Bionic-Face-Cream-12.webp', 170, 20, 'Benecos', 1, 'A-DERMA'),
(23, 'Eye liner marron certifie bio', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', '41RFsmPau9L.jpg', 120, 20, 'Nuxe', 1, 'A-DERMA'),
(24, 'bionike eye gel anti poches 15ml', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', '51tFuzH52iL._SL1000_43d8b682-0513-4ca6-a44d-c6037a038cbe_ORIGINAL.jpg', 120, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(25, 'avril anti cernes liquide', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'a29fb915df1e58a36196ebc094f4147c.jpg', 120, 20, 'Avene', 1, 'ACTI CEUTIC'),
(26, 'avril eyeliner bio', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'avril-eyeliner-bio.jpg', 180, 20, 'Eucerin', 1, 'ACORELLE'),
(27, 'base de teint 30ml', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'base-de-teint-30ml-avril.jpg', 210, 20, 'Eucerin', 1, 'ALBADERME'),
(28, 'beauty charm eponge de maquillage orange', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'beauty-charm-eponge-de-maquillage-orange-.jpg', 210, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(29, 'bionike eye gel anti poches 15ml', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'bionike-eye-gel-anti-poches-15ml-promo-parapharmacie-casablanca-maroc-medical-media-store-300x300.jpg', 240, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(30, 'cotoneve coton disque bio line 60pcs', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'cotoneve-coton-disque-bio-line-60pcs-promo-parapharmacie-casablanca-maroc-medical-media-store.jpg', 240, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(31, 'd25a1878 8350 4c88 b965 572c8a47f5af', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'd25a1878-8350-4c88-b965-572c8a47f5af.jpg', 90, 20, 'Bingo', 1, 'ACORELLE'),
(32, 'ecotools start the day beautifully', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'ecotools-start-the-day-beautifully-kit-parfumerie-parapharmacie-palmarosa-shop-maroc-en-ligne-discount.jpg', 90, 20, 'Avene', 1, 'ACTI CEUTIC'),
(33, 'Eye liner marron certifie bio Avril', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'Eye-liner-marron-certifie-bio-Avril.jpg', 110, 20, 'Avene', 1, 'A-DERMA'),
(34, 'fond de teint match perfection', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'fond-de-teint-match-perfection.jpg', 110, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(35, 'jomtam', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'jomtam.jpg', 200, 20, 'Avene', 1, 'ALBADERME'),
(36, 'l oreal paris ultra matte liquid lipstick', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'l-oreal-paris-ultra-matte-liquid-lipstick-864-parfumerie-parapharmacie-palmarosa-shop-en-ligne-discount.jpg', 200, 20, 'Bingo', 1, 'A-DERMA'),
(37, 'md bio12 lotion antipelliculaire 150ml', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'md-bio12-lotion-antipelliculaire-150ml-promo-parapharmacie-casablanca-maroc-medical-media-store.jpg', 150, 20, 'Bingo', 1, 'ALBADERME'),
(38, 'mua satin sheen stylo pour levres', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'mua-satin-sheen-stylo-pour-levres.jpg', 150, 20, 'Avene', 1, 'A-DERMA'),
(39, 'nuxe poudre eclat', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'nuxe-poudre-eclat.jpg', 60, 20, 'Eucerin', 1, 'ACTI CEUTIC'),
(40, 'xctmpG61Vdy', 'maquillage', 'Natural Quattro Eyeshadow 4 combinaisons de couleurs True Blue. Une base pour lisser et illuminer, deux teintes moyennes et une teinte fumée pour un regard intense. Les pigments se caractérisent par une intensité, un éclat et une texture soyeuse qui garantissent des performances de couleur ultimes et suprêmes', 'xctmpG61Vdy.jpg', 60, 20, 'Avene', 1, 'ACORELLE'),
(41, 'urgo compresse sterile', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'urgo-compresse-sterile-40cm40cm-b10.jpg', 120, 20, 'Nuxe', 1, 'ACORELLE'),
(42, 'Urgo Bande De Gaz 5cm', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Urgo-Bande-De-Gaz-5cm.webp', 120, 20, 'Eucerin', 1, 'A-DERMA'),
(43, 'st ives parfumerie', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'st-ives-nettoyant-corporel-exfoliant-apricot-parfumerie.jpg', 150, 20, 'Avene', 1, 'A-DERMA'),
(44, 'st ives nettoyant', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'st-ives-nettoyant-corporel-exfoliant-apricot.jpg', 150, 20, 'Nuxe', 1, 'A-DERMA'),
(45, 'st ives corporel', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'st-ives-nettoyant-corporel.avif', 180, 20, 'Nuxe', 1, 'A-DERMA'),
(46, 'Ortholand Echarpe', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Ortholand-Echarpe-de-bras-Noir-small.webp', 180, 20, 'Nuxe', 1, 'ACORELLE'),
(47, 'omabeta body corset', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'omabeta-body-corset-shaper-cuisse-plus-mince-body.webp', 80, 20, 'Avene', 1, 'ACTI CEUTIC'),
(48, 'nivea body lotion hydratante', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'nivea-body-lotion-hydratante.webp', 80, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(49, 'MGD NATURE body', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', '.jpg', 220, 20, 'Bingo', 1, 'ACORELLE'),
(50, 'lait corps nourrissant 400ml', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'lait-corps-nourrissant-400ml.jpg', 220, 20, 'Avene', 1, 'ACORELLE'),
(51, 'corps nourrissant 400ml', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'corps-nourrissant-400ml.jpg', 90, 20, 'Avene', 1, 'ACORELLE'),
(52, 'body fine elastic poignet', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'body-fine-elastic-poignet.jpg', 90, 20, 'Bingo', 1, 'A-DERMA'),
(53, 'Body Fine Elastic', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Body-Fine-Elastic-genouillere.webp', 100, 20, 'Eucerin', 1, 'ACORELLE'),
(54, 'body fine elastic', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'body-fine-elastic-chevillere-l.jpg', 100, 20, 'Bingo', 1, 'ACORELLE'),
(55, 'echarpe de bras gm', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'body-fine-echarpe-de-bras-gm.jpg', 120, 20, 'Benecos', 1, 'A-DERMA'),
(56, 'Ceinture Abdominale', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Body-Fine-Ceinture-Abdominale.webp', 120, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(57, 'Body Detox 10 Monodoses', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Body-Detox-10-Monodoses.webp', 60, 20, 'Benecos', 1, 'ACORELLE'),
(58, 'Detox 10 Monodoses', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Detox-10-Monodoses.jpg', 60, 20, 'Eucerin', 1, 'ACTI CEUTIC'),
(59, 'body Monodoses', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'body-Detox-Monodoses.webp', 200, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(60, 'Detox Monodoses  50 ml', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'body-Detox-Monodoses-50-ml.webp', 200, 20, 'Nuxe', 1, 'ACORELLE'),
(61, 'corps Monodoses', 'body', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'corps-Detox-Monodoses-50-ml.jpg', 300, 20, 'Avene', 1, 'ACORELLE'),
(62, 'vichy nutrients masque', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'vichy-dercos-nutrients-masque-nourrissant.jpg', 300, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(63, 'uriage ds hair shampooing', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'uriage-ds-hair-shampooing-equilibrant-200-ml-.jpg', 300, 20, 'Avene', 1, 'ALBADERME'),
(64, 'penta hair tr masque 500 ml', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'penta-hair-tr-masque-500-ml.jpg', 300, 20, 'Avene', 1, 'ACORELLE'),
(65, 'palmer s serum capillaire', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'palmer-s-serum-capillaire-cheveux-secs-et-abimes-178ml.webp', 200, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(66, 'nature soin huile', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'nature-soin-huile-capillaire-a-lhuile-dolive-tous-types-de-cheveux125-ml.webp', 200, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(67, 'nature huile capillaire', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'nature-soin-huile-capillaire-10-tous-types-de-cheveux-125ml.webp', 200, 20, 'Avene', 1, 'ACORELLE'),
(68, 'Marrak Hair Recovery', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Marrak-Hair-Recovery-Spray-59ml.webp', 210, 20, 'Nuxe', 1, 'ACORELLE'),
(69, 'luxeol huile de ricin', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'luxeol-huile-de-ricin-50ml.webp', 120, 20, 'Eucerin', 1, 'A-DERMA'),
(70, 'hairburst for longer stronger hair', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'hairburst-for-longer-stronger-hair-shampoo-60ml.webp', 120, 20, 'Nuxe', 1, 'ACORELLE'),
(71, 'Ecrinal Shampooing', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Ecrinal-Shampooing-Ultra-Doux-400ml.webp', 120, 20, 'Avene', 1, 'A-DERMA'),
(72, 'Ecrinal Capillaire', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Ecrinal-ANP-2_-Masque-Capillaire.webp', 90, 20, 'Nuxe', 1, 'ACTI CEUTIC'),
(73, 'dcp hairloss lotion', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'dcp-hairloss-lotion-capillaire-femmes-200ml.webp', 90, 20, 'Bingo', 1, 'ALBADERME'),
(74, 'Apivita Spray Lotion', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Apivita-Spray-Lotion-Tonic-Anti-chute-Unisexe.webp', 100, 20, 'Bingo', 1, 'ACORELLE'),
(75, 'Apivita Shampooing', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Apivita-Shampooing-Tonic-Femme-250ml.webp', 100, 20, 'Benecos', 1, 'ALBADERME'),
(76, 'Apivita Kids Shampooing 250ml', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Apivita-Kids-Shampooing-250ml.webp', 190, 20, 'Nuxe', 1, 'ACTI CEUTIC'),
(77, 'APIVITA RESCUE NOURISH', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'APIVITA-RESCUE-NOURISH-REPAIR-HAIR-OIL-100-ML-ARGAN.jpg', 190, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(78, 'dcp hair loss masque', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'dcp-hair-loss-masque-capillaire-200-ml.jpg', 190, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(79, 'DS HAIR LOTION 100 ML', 'hair', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'DS-HAIR-LOTION-100-ML.jpg', 95, 20, 'Benecos', 1, 'ACORELLE'),
(80, 'Baby Cocole Pommade Creme', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Baby-Cocole-Pommade-Creme-De-Change-30ml.webp', 95, 20, 'Benecos', 1, 'A-DERMA'),
(81, 'Babyheart Creme', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Babyheart-Creme-De-Change-150ml.webp', 95, 20, 'Benecos', 1, 'ACORELLE'),
(82, 'belvital mouche bebe', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'belvital-mouche-bebe.webp', 130, 20, 'Benecos', 1, 'A-DERMA'),
(83, 'ecolunes lessive bebe', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'ecolunes-lessive-bebe.webp', 130, 20, 'Eucerin', 1, 'ACORELLE'),
(84, 'Gum BABY Brosse a Dents', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Gum-BABY-Brosse-a-Dents.webp', 130, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(85, 'johnsons baby Talc 200gr', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'johnsons-baby-Talc-200gr.webp', 160, 20, 'Bingo', 1, 'ALBADERME'),
(86, 'lansinoh creme mamelons', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'lansinoh-creme-mamelons-hpa-lanoline-40-ml.webp', 160, 20, 'Nuxe', 1, 'ALBADERME'),
(87, 'lansinoh organic nipple', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'lansinoh-organic-nipple-balm-60ml.webp', 160, 20, 'Eucerin', 1, 'ACTI CEUTIC'),
(88, 'Neutraderm Baby Gel', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Neutraderm-Baby-Gel-Nettoyant-Douceur-3-En-1-400ml.webp', 240, 20, 'Nuxe', 1, 'ACTI CEUTIC'),
(89, 'ORAL B DENTIFRICE BABY', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'ORAL-B-DENTIFRICE-BABY-0-2-ANS.webp', 240, 20, 'Eucerin', 1, 'A-DERMA'),
(90, 'Ultrasun Baby Mineral Solaire', 'baby', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Ultrasun-Baby-Mineral-Solaire.webp', 290, 20, 'Benecos', 1, 'A-DERMA'),
(91, 'Vertu Plus Zinc', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Vertu-Plus-Zinc-Plus-60-Gelules.webp', 290, 20, 'Benecos', 1, 'ACORELLE'),
(92, 'Vertu Plus Collagene Marin', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Vertu-Plus-Collagene-Marin.webp', 275, 20, 'Bingo', 1, 'A-DERMA'),
(93, 'Spirit Collagene', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Spirit-Collagene-Marin-Vitamine-C.webp', 275, 20, 'Bingo', 1, 'A-DERMA'),
(94, 'Ocaflor Spray', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Ocaflor-Spray-Antiseptique-120ml.webp', 275, 20, 'Avene', 1, 'ACTI CEUTIC'),
(95, 'Hydra  Health', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Hydra-Phyt_s-Osteo-Health.webp', 275, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(96, 'Hydra Melatonine Sommeil', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Hydra-Phyt_s-Melatonine-Sommeil.webp', 120, 20, 'Eucerin', 1, 'ACORELLE'),
(97, 'H_S Line Spray Antiseptique 120ml', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'H_S-Line-Spray-Antiseptique-120ml.webp', 120, 20, 'Eucerin', 1, 'ACORELLE'),
(98, 'Line Spray ', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'H_S-Line-Spray-Antiseptique.webp', 120, 20, 'Eucerin', 1, 'ACORELLE'),
(99, 'zo_skin retinol parfumerie', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'zo_skin-retinol-parfumerie.jpg', 120, 20, 'Benecos', 1, 'ALBADERME'),
(100, 'vitabiotics osteocare calcium', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'vitabiotics-osteocare-calcium.jpg', 150, 20, 'Avene', 1, 'ACTI CEUTIC'),
(101, 'hs line creme depigmente 50ml', 'health', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'hs-line-creme-depigmente-50ml.jpg', 150, 20, 'Nuxe', 1, 'A-DERMA'),
(102, 'yves ponroy ginseng ginkgo', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'yves-ponroy-ginseng-ginkgo.jpg', 200, 20, 'Benecos', 1, 'ACORELLE'),
(103, 'yves ponroy gelee', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'yves-ponroy-gelee-royale-ampoules-10-amp.jpg', 200, 20, 'Bingo', 1, 'ACORELLE'),
(104, 'yves gelee royale', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'yves-gelee-royale.jpg', 200, 20, 'Benecos', 1, 'ACORELLE'),
(105, 'gph diffusion ginseng', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'gph-diffusion-ginseng-bio-120-comprimes.jpg', 100, 20, 'Avene', 1, 'ALBADERME'),
(106, 'ginkgo biloba', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'ginkgo-biloba.jpg', 100, 20, 'Eucerin', 1, 'ACTI CEUTIC'),
(107, 'Forte Royal Gelee', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Forte-Royal-Gelee-Royale-1000-mg.jpg', 100, 20, 'Bingo', 1, 'ALBADERME'),
(108, 'dietaroma la ruche gelee', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'dietaroma-la-ruche-gelee.jpg', 120, 20, 'Avene', 1, 'ACORELLE');
INSERT INTO `produits` (`id`, `title`, `type`, `description`, `src`, `price`, `qte`, `company`, `qtecart`, `marque`) VALUES
(109, 'dietaroma la ruche', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'dietaroma-la-ruche.jpg', 120, 20, 'Eucerin', 1, 'A-DERMA'),
(110, 'Vitalina Spiruline Bio', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Vitalina-Spiruline-Bio.webp', 120, 20, 'Benecos', 1, 'ALBADERME'),
(111, 'so bio lait corps', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'so-bio-lait-corps-hydratant-lait-danesse-200ml.webp', 120, 20, 'Avene', 1, 'ACTI CEUTIC'),
(112, 'so bio deo soin', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'so-bio-deo-soin-fraicheur-menthe-50ml.webp', 120, 20, 'Avene', 1, 'ACORELLE'),
(113, 'Bio Oil Gel Peaux', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Bio-Oil-Gel-Peaux-Seches-100ml.webp', 120, 20, 'Benecos', 1, 'ALBADERME'),
(114, 'moringa bio', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'moringa-bio-200-gelules.png', 120, 20, 'Eucerin', 1, 'ACTI CEUTIC'),
(115, 'moringa 60 capsules 800mg', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'moringa-60-capsules-800mg.png', 120, 20, 'Eucerin', 1, 'ACORELLE'),
(116, 'jardin bio ventre plat', 'natural', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'jardin-bio-ventre-plat.png', 120, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(117, 'uriage gyn phy gel', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'uriage-gyn-phy-gel-fraicheur-hygiene-intime-200ml.webp', 100, 20, 'Bingo', 1, 'A-DERMA'),
(118, 'sterimar spray nasal 100ml', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'sterimar-spray-nasal-100ml.webp', 150, 20, 'Eucerin', 1, 'A-DERMA'),
(119, 'sterimar spray nasal', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'sterimar-spray-nasal.webp', 150, 20, 'Nuxe', 1, 'ACORELLE'),
(120, 'mustela gel hygiene', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'paralive.ma_-_mustela_gel_hygiene_intime_200ml.webp', 150, 20, 'Avene', 1, 'ACORELLE'),
(121, 'Humer Hygiene', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Humer-Hygiene-Du-Nez-Adulte-150ml.webp', 90, 20, 'Eucerin', 1, 'ACTI CEUTIC'),
(122, 'Nourrisson Et Enfant 150ml', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Humer-Hygiene-De-Nez-Nourrisson-Et-Enfant-150ml.webp', 90, 20, 'Avene', 1, 'ACORELLE'),
(123, 'Gilbert A Cerumen Hygiene', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Gilbert-A-Cerumen-Hygiene.webp', 90, 20, 'Avene', 1, 'ALBADERME'),
(124, 'Cumlaude lab Hygiene', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Cumlaude-lab-Hygiene-Intime-Diara-200ml.webp', 60, 20, 'Nuxe', 1, 'A-DERMA'),
(125, 'sterimar bebe spray', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'sterimar-bebe-spray-hygiene-du-nez-50-ml.jpg', 200, 20, 'Benecos', 1, 'ACORELLE'),
(126, 'placentor gel', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'placentor-gel-nettoyant-hygiene-intime-200ml.jpg', 200, 20, 'Nuxe', 1, 'ACORELLE'),
(127, 'intime muqueuses ', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'intime-muqueuses-sensibles-200Ml.jpg', 320, 20, 'Eucerin', 1, 'A-DERMA'),
(128, 'muqueuses sensibles', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'muqueuses-sensibles.jpg', 320, 20, 'Benecos', 1, 'ACORELLE'),
(129, 'cumlaude lab hygiene intime', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'cumlaude-lab-hygiene-intime-pediatrics-250ml.jpg', 420, 20, 'Bingo', 1, 'ACORELLE'),
(130, 'cattier gynea hygiene intime 200ml', 'hygiene', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'cattier-gynea-hygiene-intime-200ml.jpg', 420, 20, 'Eucerin', 1, 'A-DERMA'),
(131, 'Isispharma Uveblock SPF', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Isispharma-Uveblock-SPF.webp', 120, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(132, 'Uveblock SPF', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Uveblock-SPF.webp', 120, 20, 'Nuxe', 1, 'A-DERMA'),
(133, 'Isispharma Uveblock Creme', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Isispharma-Uveblock-Creme.webp', 210, 20, 'Bingo', 1, 'ACTI CEUTIC'),
(134, 'Heliabrine Ecran Solaire Defense', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Heliabrine-Ecran-Solaire-Defense.webp', 210, 20, 'Avene', 1, 'A-DERMA'),
(135, 'Eucerin Sun', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Eucerin-Sun.webp', 300, 20, 'Benecos', 1, 'A-DERMA'),
(136, 'CHOLLEY Alpine Defense', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'CHOLLEY-Alpine-Defense.webp', 300, 20, 'Nuxe', 1, 'A-DERMA'),
(137, 'avene solaire spray spf 50 enfant 200ml', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'avene-solaire-spray-spf-50-enfant-200ml.webp', 140, 20, 'Avene', 1, 'ACORELLE'),
(138, 'acorelle spray solaire enfants', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'acorelle-spray-solaire-enfants.webp', 140, 20, 'Benecos', 1, 'ACORELLE'),
(139, 'acorelle preparateur', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'acorelle-soin-preparateur-de-bronzage-bio-100ml.webp', 120, 20, 'Bingo', 1, 'ALBADERME'),
(140, 'acorelle soin preparateur', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'acorelle-soin-preparateur.webp', 120, 20, 'Eucerin', 1, 'A-DERMA'),
(141, 'Ultrasun extrem gel solaire 75ml', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Ultrasun-extrem-gel-solaire-75ml.jpg', 180, 20, 'Bingo', 1, 'ACORELLE'),
(142, 'Fotoprotecteur Hydro oil 200ml', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Fotoprotecteur-Hydro-oil-200ml.jpg', 180, 20, 'Avene', 1, 'ACTI CEUTIC'),
(143, 'Fotoprotecteur Hydro oil', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Fotoprotecteur-Hydro-oil.jpg', 180, 20, 'Benecos', 1, 'ACTI CEUTIC'),
(144, 'Fotoprotecteur Hydro oil 45ml', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'Fotoprotecteur-Hydro-oil-45ml.jpg', 180, 20, 'Nuxe', 1, 'ACORELLE'),
(145, 'heliocare pigment fluid parfumerie', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'heliocare-pigment-fluid-parfumerie.jpg', 240, 20, 'Benecos', 1, 'ACORELLE'),
(146, 'isdin fotoprotector', 'solar', 'Ravivez votre peau impeccable avec l\'huile thérapeutique pour la peau au beurre de cacao de Palmer\'s. Il hydrate et aide à lisser votre peau, la laissant merveilleusement douce, revitalisée et d\'apparence saine. Cette huile de thérapie de la peau est parfaite pour les cicatrices, les vergetures, la peau sèche et endommagée, le teint irrégulier et le vieillissement de la peau. ', 'isdin-fotoprotector-uv-mineral-brush-spf50-2g.jpg', 240, 20, 'Nuxe', 1, 'A-DERMA');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `produits`
--
ALTER TABLE `produits`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `produits`
--
ALTER TABLE `produits`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=147;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
